format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
format_strings = true
fn_single_line = true
merge_imports = true
wrap_comments = true
chain_width = 80
