[defaults]
base_url = "https://github.com"
api_base_url = "https://api.github.com/repos"

[defaults.platform.macos]
aarch64 = "aarch64-apple-darwin"
x86_64 = "x86_64-apple-darwin"

[defaults.platform.linux]
x86_64 = "x86_64-unknown-linux-gnu"

[defaults.platform.windows]
x86_64 = "win64"

[defaults.ext]
macos = "tar.gz"
linux = "tar.gz"
windows = "zip"

[[org]]
name = "txpipe"

[[org.package]]
id = "oura"
alias = "oura"
repo = "oura"
download_template = "{base}/{repo}/releases/download/{version}/oura-{platform}.{file_type}"

[org.package.platform.linux]
x86_64 = "x86_64-unknown-linux-musl"

[org.package.ext]
macos = "tar.xz"
linux = "tar.xz"
